<?php
/**
 * @var $block \Shopgate\Import\Block\Adminhtml\Order\View\View
 */
if ($block->isShopgateOrder()) { ?>
    <style>
        #shopgate-order-block ul {
            list-style: none;
        }

        #shopgate-order-block ul ul {
            margin: 5px 0 0 10px;
        }

        #shopgate-order-block ul li {
            margin: 5px 0;
        }
    </style>
    <section id="shopgate-order-block" class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title">Shopgate Order Information</span>
        </div>
        <div class="admin__page-section-content">
           <?php echo $block->printData(); ?>
        </div>
    </section>
<?php } ?>
